# Generated by Django 5.0.3 on 2024-04-04 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eoi', '0001_initial'),
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eoi',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eois', to='workshops.workshop'),
        ),
    ]
