# Generated by Django 5.0.3 on 2024-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='eoi_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
