# Generated by Django 5.0.3 on 2024-03-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoi', '0002_eoi_eoi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='eoi_type',
            field=models.CharField(choices=[('Organise', 'Organise'), ('Attend', 'Attend'), ('Mentor', 'Mentor')], default='Attend', max_length=10),
        ),
    ]
