# Generated by Django 5.0.3 on 2024-03-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='status',
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
